//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_ShopDunk_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public Color()
        {
            this.ProductDetail = new HashSet<ProductDetail>();
        }
    
        public int IDColor { get; set; }
        public string ColorName { get; set; }
        public string RGB { get; set; }
    
        public virtual ICollection<ProductDetail> ProductDetail { get; set; }
    }
}
