//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_ShopDunk_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public ProductDetail()
        {
            this.Images = new HashSet<Images>();
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int IDProDe { get; set; }
        public Nullable<int> IDPro { get; set; }
        public Nullable<int> IDOrDe { get; set; }
        public Nullable<int> IDColor { get; set; }
        public string TenSPCT { get; set; }
        public string DanhGia { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual ICollection<Images> Images { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Product Product { get; set; }
    }
}
