//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_ShopDunk_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductDetail = new HashSet<ProductDetail>();
        }
    
        public int IDPro { get; set; }
        public Nullable<int> IDCate { get; set; }
        public string NamePro { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public string ChiTietSP { get; set; }
        public string ThongSoKyThuat { get; set; }
        public string MoTa { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ProductDetail> ProductDetail { get; set; }
    }
}
